services:
  - type: web
    name: secondlife
    env: docker
    plan: free
    envVars:
      - key: GIN_MODE
        value: release
      - key: MONGO_URI
        fromDatabase:
          name: secondlife-mongo
          property: connectionString

databases:
  - name: secondlife-mongo
    plan: starter
    databaseName: secondlife
    ipAllowList: []